### ISSUE TITLE
新能源是否已经处于高位，什么时候下车比较好？

### ISSUE THREAD

**Issue by bohehe** [kangfenmao/stock-weekly#2]

**Comment by kangfenmao** [comment]
抖音搜索谢小宝财经，看看他近期2个视频，立马对板块进行了分析。按理说，能源板块资金在悄悄出。另外一个观点如下图

![image](https://user-images.githubusercontent.com/8253512/145342858-f2012c54-73a7-499a-9ba6-c35c82101fe2.png)

买卖必须依靠自己判断

**Comment by kangfenmao** [comment]
在高位，随时下车，换低位的券商，A50成分股

**Comment by bohehe** [comment]
我悟了，多谢大师
